Add external data checker metadata for firefox extra-data
endlessm/firefox-flatpak pull request #42
Opened 2019-08-07 00:35 UTC by andrunko

Depends on https://github.com/endlessm/flatpak-external-data-checker/pull/28.

https://phabricator.endlessm.com/T22543

2019-08-07 02:37 UTC, andrunko commented
Force-pushed after rebase.

2019-08-16 06:29 UTC, wjt requested changes

2019-08-16 06:29 UTC, wjt commented on org.mozilla.Firefox.json
> +                "browser": {
As described on https://github.com/endlessm/flatpak-external-data-checker/pull/28 I think it should be enough to specify `"type": "firefox"` – this checker is completely Firefox-specific so I don't see much value in generalizing the filenames.

2019-08-20 15:37 UTC, wjt approved these changes

2019-08-20 15:37 UTC, merged